spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://paascloud-db-mysql:3306/paascloud_uac?characterEncoding=utf8&useSSL=false

mybatis:
  type-aliases-package: com.ucar.shopcloud.provider.model.domain
  mapper-locations: classpath:mapper/*.xml,classpath*:sdk/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: com.ucar.shopcloud.common.core.mybatis.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

liquibase:
  change-log: classpath:liquibase/index.xml
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  url: ${spring.datasource.url}

security:
  oauth2:
    client:
      clientId: paascloud-client-uac
      clientSecret: paascloudClientSecret
      access-token-uri: http://paascloud-gateway:7979/uac/oauth/token
      user-authorization-uri: http://paascloud-gateway:7979/uac/oauth/authorize
    resource:
      id: paascloud-resource-uac
      filter-order: 3
